version = 0.1
[default.deploy.parameters]
stack_name = "chrome-web-store-scraper"
resolve_s3 = true
s3_prefix = "chrome-web-store-scraper"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "TableName=\"ChromeWebStoreItem\""
image_repositories = []
